---
- hosts: localhost  # put localhost.  We are processing against aws
  connection: local  # put local.  We are processing against aws
  gather_facts: False  # don't gather facts against localhost
  tasks:  
  - name: Create Honey Pot Security Group
    ec2_group:
      name: SGHoneyPot
      description: DMZ Security Group
      vpc_id: "{{ vpc_id }}"
      region: "{{ region }}"
      rules:
        - rule_desc: Allow all inbound traffic
          proto: -1
          ports: -1
          cidr_ip: "{{ destinationCidrBlock }}"
    register: SGHP

  - name: Set HP SG ID in variable
    set_stats:
      data:
        security_group_hp: "{{ SGHP }}"
        
  - name: Create Gateway Security Group
    ec2_group:
      name: SGGateway
      description: DMZ Security Group
      vpc_id: "{{ vpc_id }}"
      region: "{{ region }}"
      rules:
        - rule_desc: Allow all inbound traffic
          proto: -1
          ports: -1
          cidr_ip: "{{ destinationCidrBlock }}"
    register: SGGW

  - name: Set Gateway SG ID in variable
    set_stats:
      data:
        security_group_Gateway: "{{ SGGW }}"

  - name: Create Management Security Group
    ec2_group:
      name: SGManagenet
      description: DMZ Security Group
      vpc_id: "{{ vpc_id }}"
      region: "{{ region }}"
      rules:
        - rule_desc: Allow all from vpc 
          proto: -1
          ports: -1
          cidr_ip: "{{ vpc_cidr }}"
        - rule_desc: Allow ssh
          proto: tcp
          ports: 22
          cidr_ip: "{{ destinationCidrBlock }}"
        - rule_desc: Allow https
          proto: tcp
          ports: 443
          cidr_ip: "{{ destinationCidrBlock }}"
        - rule_desc: Allow 18190
          proto: tcp
          ports: 18190
          cidr_ip: "{{ destinationCidrBlock }}"
        - rule_desc: Allow 19009
          proto: tcp
          ports: 19009
          cidr_ip: "{{ destinationCidrBlock }}"
    register: SGMGMT

  - name: Set MgMT SG ID in variable
    set_stats:
      data:
        security_group_mgmt: "{{ SGMGMT }}"
