---
- hosts: localhost  # put localhost.  We are processing against aws
  connection: local  # put local.  We are processing against aws
  gather_facts: False  # don't gather facts against localhost
  tasks:
  - name: launche honeyPot
    ec2:
      region: "{{ region }}"
      image: "{{ hp_ami.msg }}"
      instance_type: "{{ hp_hw }}"
      private_ip: "{{ hp_net3_ip }}"
      wait: no
      group_id: "{{ security_group_hp.group_id }}"
      vpc_subnet_id: "{{ subnet3.subnet.id }}"
      key_name: "{{ keypairName  }}"
      assign_public_ip: false
      instance_tags: 
        Name: HoneyPotEC2      
    register: HPInstance 
