- name: Activate core protection Host Port Scan on the Optimized protection profile
  check_point.mgmt.cp_mgmt_threat_protection_override:
    name: Host Port Scan
    overrides:
    - action: Accept
      #capture_packets: false
      profile: Optimized
      track: log
  notify: Publish and install handler