---
# Task to identify any reconnaissance attacks in form of portscans in the security logs
# The variables used is defined in ../defaults/main.yml of this role.
# The task requires core protection Host Port Scan to be activated.
- name: identify any reconnaissance attacks
  check_point.mgmt.cp_mgmt_show_logs:
    new_query:
      filter: attack:"Port Scan"
      max_logs_per_request: 1
      time_frame: last-hour
  register: show_log_response

# Get the source IP in the log entry
- name : Get the attacker source IP from the log entry 
  set_fact:
     attacker_src_ip: "{{ show_log_response['show-logs'].logs[0].src }}"
  when: show_log_response['show-logs'].logs[0].src is defined

# Get destination IP in the log entry
- name : Get the target destination IP from the log entry
  set_fact:
     target_dst_ip: "{{ show_log_response['show-logs'].logs[0].dst }}"
  when: show_log_response['show-logs'].logs[0].dst is defined